version: "3.9"

services:
  opryscrape:
    image: opryscrape/app
    build:
      context: ./backend
    ports:
    - 8080:8080
    environment:
      DATABASE_PATH: "/app/data/opry.db"
      DB_BATCH_SIZE: 30
      FLUSH_SECONDS: 60
      PORT: 8080
    volumes:
    - ./data:/app/data

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

  test:
    build:
      context: ./backend
      target: build
    working_dir: /src
    command: go test ./... -v